<?php

/**
 * @file
 * General functions and hook implementations.
 */

use Drupal\Core\DrupalKernel;
use Drupal\datetime_flatpickr\Constants\AvailableLanguages;

/**
 * Implements hook_library_info_alter().
 */
function datetime_flatpickr_library_info_alter(array &$libraries, $module) {
  if ('datetime_flatpickr' == $module) {
    if (isset($libraries['flatpickr'])) {
      $flatpickr_js_path = _datetime_flatpickr_get_flatpickr_path();
      if (!$flatpickr_js_path) return;
      $libraries['flatpickr'] = [];
      $minified = file_exists($flatpickr_js_path . '/flatpickr.min.js');
      $flatpickr_js_path = '/' . $flatpickr_js_path;
      $flatpickr_js = $minified
        ? $flatpickr_js_path . '/flatpickr.min.js'
        : $flatpickr_js_path . '/flatpickr.js';
      $libraries['flatpickr']['js'][$flatpickr_js] = [
        'minified' => $minified,
      ];
      $flatpickr_css = $flatpickr_js_path . '/flatpickr.min.css';
      $libraries['flatpickr']['css']['theme'][$flatpickr_css] = [
        'minified' => $minified,
      ];

      $languages = AvailableLanguages::LANGUAGES;

      foreach ($languages as $language) {
        $flatpickr_lang = $flatpickr_js_path . '/l10n/' . $language . '.js';
        $libraries['flatpickr_' . mb_strtolower($language)] = [];
        $libraries['flatpickr_' . mb_strtolower($language)]['js'][$flatpickr_lang] = [];
      }

    }
  }
}

/**
 * Get the location of the flatpickr library.
 *
 * @return string
 *   The location of the library, or FALSE if the library isn't installed.
 */
function _datetime_flatpickr_get_flatpickr_path() {

  $searchdir = [];

  $searchdir[] = 'profiles/' . \Drupal::installProfile() . '/libraries/';

  $searchdir[] = 'libraries/';

  $searchdir[] = DrupalKernel::findSitePath(\Drupal::request()) . '/libraries/';

  foreach ($searchdir as $dir) {
    foreach (['flatpickr/dist'] as $sub) {
      if (file_exists($dir . $sub . '/flatpickr.js')) {
        return $dir . $sub;
      }
    }
  }

  return FALSE;
}
